config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  resources :splash, only: [:index]
  resources :groups do
    resources :expenses
  end

  resources :not_found, only: [:index]
  # Defines the root path route ("/")
  # root "articles#index"
  root 'splash#index'

  get '/unauthorized', to: 'unauthorized#index'

  match '*unmatched', to: 'application#not_found_method', via: :all, constraints: ->(req) do
    req.path.exclude? 'rails/active_storage'
  end
end

app/models/group.rb
class Group < ApplicationRecord
  belongs_to :user, class_name: 'User', foreign_key: 'user_id'
  has_many :group_expenses
  has_many :expenses, through: :group_expenses

  has_one_attached :icon

  validates :name, presence: true, length: { in: 2..300 }
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  load_and_authorize_resource

  before_action :find_user
  before_action :find_group, only: %i[show edit update destroy]

  def index
    @groups = @user.groups.all
  end

  def show; end

  def new
    @group = Group.new
  end

  def create
    @group = Group.new(group_params)
    @group.user = @user
    if @group.save
      redirect_to groups_path, notice: 'Group created successfully'
    else
      flash.now[:alert] = @group.errors.full_messages.first if @group.errors.any?
      render :new, status: 400
    end
  end

  def edit; end

  def update
    if @group.update(group_params)
      redirect_to group_path(id: @group.id), notice: 'Group updated successfully'
    else
      flash.now[:alert] = @group.errors.full_messages.first if @group.errors.any?
      render :edit, status: 400
    end
  end

  # rubocop:disable Lint/UselessAssignment
  def destroy
    if can? :edit, @group
      @group_expenses = GroupExpense.where(group_id: @group.id)
      @group_expenses.each do |group_expense|
        expense_id = group_expense.expense_id
        group_expense.destroy
        expense = Expense.delete(expense_id)
      end
      if @group.destroy
        redirect_to groups_path, notice: 'Groups was deleted successfully'
      else
        flash.now[:alert] = @group.errors.full_messages.first if @group.errors.any?
        render :index, status: 400
      end
    else
      flash[:alert] = 'Un Authorized'
      redirect_to groups_path
    end
  end
  # rubocop:enable Lint/UselessAssignment

  private

  def find_user
    @user = current_user
  end

  def find_group
    @group = Group.find(params[:id])
  rescue ActiveRecord::RecordNotFound
    flash[:alert] = 'Group not found!'
    redirect_to not_found_index_path
  end

  def group_params
    params.require(:group).permit(:name, :icon)
  end
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/_header.html.erb
<h1>Categories</h1>

app/views/groups/edit.html.erb
<%= render "groups/header" %>
<section class="categories">
  <div class="splash__data">
  <%= form_with model: @group, url: group_path(id: @group.id), local: true, class: "form_gen" do |f| %>
    <%= f.text_field :name, autofocus: true, class: "splash__input box" %>
    <%= f.file_field :icon, class: "splash__input box" %>
    <div class="form_btn">
      <%= f.submit "Update Category", class: 'btn primary_btn btn_txt' %>
    </div>
  <% end %>
  </div>
</section>

<div class="new_item">
  <%= link_to 'Back', group_path(id: @group.id), class: "btn secondary_btn btn_txt" %>
</div>

app/views/groups/index.html.erb
<%= render "groups/header" %>
<div class="categories"> 
 <% if @groups.any?  %>
  
    <div class="width_desk">

      <% @groups.each do |group| %>

      <div class="category">

        <div class="category__data">
          <a href=<%= group_expenses_path(group_id: group.id) %>>
            <%= image_tag(group.icon.attached? ? group.icon : 'store-icon.jpg') %>
            <div>
              <h2><%= group.name %></h2>
              <% if Time.now - group.created_at <= 1.minute %>
                <p class="category__time"><%= time_ago_in_words(group.created_at, include_seconds: true) %> ago</p>
              <% elsif Time.now - group.created_at <= 24.hours %>
                <p class="category__time"><%= time_ago_in_words(group.created_at) %> ago</p>
              <% else %>
                <p class="category__time"><%= group.created_at.strftime('%b %d, %Y') %></p>
              <% end %>
            </div>
          </a>
        </div>

        <div class="category__bill">
          <div class="btn_list">
            <button class="category__addbill"><%= link_to 'Detail', group_path(id: group.id) %> </button>
            <button class="category__addbill"><%= link_to 'Add Bill', group_expenses_path(group_id: group.id) %> </button>  
          </div>
          <div class="total_cat" >$<%= group.expenses.sum(:amount) %></div>
        </div>
      </div>

      <% end %>

    </div>

  

  <% else %>
  <div class="flash-notice">Currently, you have no categories. Add a new category to record expenses</div>
  <% end %>

</div>

  <div class="new_item">
      <%= link_to 'New Category', new_group_path, class: "btn secondary_btn btn_txt" %>
  </div>

app/views/groups/new.html.erb
<%= render "groups/header" %>
<section class="categories">
  <div class="splash__data">
  <%= form_with model: @group, url: groups_path, local: true, class: "form_gen" do |f| %>
    <%= f.text_field :name, autofocus: true, placeholder: "Group name", class: "splash__input box" %>
    <%= f.file_field :icon, class: "splash__input box" %>
    <div class="form_btn">
      <%= f.submit "Create new Category", class: "btn primary_btn btn_txt" %>
    </div>
  <% end %>
  </div>
</section>

<div class="new_item">
  <%= link_to 'Back', groups_path, class: "btn secondary_btn btn_txt" %>
</div>

app/views/groups/show.html.erb
<section class="width_desk">
  
  <div class="categories">
    <div class="category__select">
      <% if @group.icon.attached?%>
        <%= image_tag(@group.icon) %>
      <%else%>
        <%= image_tag('store-icon.jpg') %>
      <%end%>
      <h2><%= @group.name %></h2>
    </div>

    <div class="total_expense"><span>TOTAL EXPENSE: $<%= @group.expenses.sum(:amount) %></span></div>
    <div class="btn_gen">
      <button class="btn_gen_edit"><%= link_to "Edit", edit_group_path(@group) %></button>
      <button class="btn_gen_edit"><%= link_to "Back", groups_path %></button>
      <%= button_to "Delete", @group, method: :delete, class: 'btn_gen_edit alert' %>
    </div>
  </div>

</section>